<a href="https://colab.research.google.com/github/gregorimaia/Engenharia_Aeroespacial/blob/main/Python_Instructions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tipos de Variáveis**
## Variável Inteira (int): Utilizada para números inteiros;
## Variável Decimal (Flutuante, float);
## Variável String (str);
## Variável Dictionary (dict);
## Variável Booleana (bool);
## Variáveis de lista: list e tuple;

Para itendificar o tipo de variável utiliza-se o comando type().


In [ ]:
# (int) Números inteiros
ano = 2022
print(ano)
print(type(ano))

# (float) Números decimais ou fracionários
idade = 26.5
print(idade)
print(type(idade))

# (str) Caracteres ou texto
nome = 'Gregori'
print(nome)
print(type(nome))

# (dict) Pares de informações relacionando-as
dict1= {'Nome':'Gregori', 'Idade':57, 'Nota':8.5}
print(dict1, type(dict1))

# (bool) Assume valores de verdadeiro (1) ou falso (0)
CodeQ = True
print(CodeQ, type(CodeQ))

# (list, tuple) Lista de outros tipos de variáveis
# (list) os elementos podem ser alterados 
# (tuple) os elementos não podem ser alterados
alunos = ['Ana', 'Mathias', 'Grégori']
print(alunos, type(alunos))

notas = (8.9, 9.5, 8.5)
print(notas, type(notas))


2022
<class 'int'>
26.5
<class 'float'>
Gregori
<class 'str'>
{'Nome': 'Gregori', 'Idade': 57, 'Nota': 8.5} <class 'dict'>
True <class 'bool'>
['Ana', 'Mathias', 'Grégori'] <class 'list'>
(8.9, 9.5, 8.5) <class 'tuple'>


# **Comando** _*append*_ **adiciona itens à uma lista já existente, geralmente utilizado dentro de laços.**


In [ ]:
lista = [] # Criação de uma lista vazia
for i in range(10): # Criação de um loop
    y = 2*i
    lista.append(y) # Adicionando o valor y á lista
print(lista)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


# **Vetores e Matrizes**


* listas

In [ ]:
numeros = [1, 2 , 3, 4]
print(numeros)
# os elementos da lista são contados desde o zero
# Posso determinar um valor a ser apresentado da lista
print(numeros[0])  
print(numeros[2])
type(numeros)

[1, 2, 3, 4]
1
3


list

In [ ]:
# posso modificar alguma variável da lista
numeros[3] = 8
print(numeros)

[1, 2, 3, 8]


* _*array*_

In [ ]:
import numpy as np # Para não ter que ficar escrevedo numpy toda hora, mas np
# arrays são variáveis da biblioteca numpy e servirão como vetores
# multiplicaçoes matriciais só podem ser aplicadas à arrays

numeros = np.array([1,2,3,4])
Matriz = np.array([[1,0,5],[0,1,8],[2,9,3]])

print(numeros, type(numeros))
print(Matriz, type(Matriz)) # Não há um type específico para matrizes, é identificado com array.
print(Matriz[1]) # Ao escolher um item da matriz, será apresentado por linha.

[1 2 3 4] <class 'numpy.ndarray'>
[[1 0 5]
 [0 1 8]
 [2 9 3]] <class 'numpy.ndarray'>
[0 1 8]


* linspace
Vetor composto por números **igualmente espaçados** entre um determinado intervalo. Será bastante utilizado para criação de um intervalo de integração que será utilizado com a função **_*odeint*_**.

In [ ]:
T1 = np.linspace(1,5,30) # Vetor começando em 1 até 5 apresentando 30 ...
# termos igualmente espaçados
print(T1, type(T1), len(T1))
# Se não determinar o número de termos, automaticamente aparecerá 50 termos.

[1.         1.13793103 1.27586207 1.4137931  1.55172414 1.68965517
 1.82758621 1.96551724 2.10344828 2.24137931 2.37931034 2.51724138
 2.65517241 2.79310345 2.93103448 3.06896552 3.20689655 3.34482759
 3.48275862 3.62068966 3.75862069 3.89655172 4.03448276 4.17241379
 4.31034483 4.44827586 4.5862069  4.72413793 4.86206897 5.        ] <class 'numpy.ndarray'> 30


* arange

In [ ]:
import numpy as np
numeros = np.arange(3) # Quando não especificamos 2 valores, começamos de 0.
print(numeros, type(numeros))

numeros2 = np.arange(3, 9) # se não esécificar o intervalo, vai apresentar unidade por unidade
print(numeros2)

numeros3 = np.arange(3, 9, 0.5) # (início, final-1(intervalo), intervalo)
print(numeros3, len(numeros3))

[0 1 2] <class 'numpy.ndarray'>
[3 4 5 6 7 8]
[3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5] 12


Note:
* Comprimento (length) de um vetor: retorna o número de elementos de um vetor, ou o número de linhas de uma matriz. Utiliza-se o comando len(A).

# **Funções**
Dentro de uma linguagem de programação, Funções são grupos de códigos que realizam algumas tarefas que, geralmente, seriam executadas várias vezes dentro de um mesmo código. A forma de escrita de uma função é separada em 4 partes:

**NOME, PARÂMETROS, CORPO E RESPOSTA (OURETORNO)**

In [ ]:
# def nome(parametros):
#     corpo
#     return  (resposta)

**NOME**

É o nome pelo qual a função será chamada em um código

**PARÂMETROS**

São as variáveis externas à função, que são necessárias para que a função seja executada (variáveis independentes). Nem sempre será necessário declarar parâmetros, poi podemos "chamar" funções para que sejam simplesmente executadas.

**CORPO**

É onde os argumentos da função serão utilizados para a execução da função.

***RESPOSTA**

É o retorno da função, ou seja, o que a função retornará de resposta. Assim como os parâmetros, nem sempre será necessário um comando de resposta, isso dependerá do objetvo da função.


In [ ]:
def calcular_pagamento(qtd_horas, valor_hora): 
  horas = float(qtd_horas)
  taxa = float(valor_hora)
  if horas <=40:
    salario=horas*taxa
  else:
    h_excd = horas - 40
    salario = 40*taxa+(h_excd*(1.5*taxa))
  return salario

Uma jornada semanal de trabalho é de horas, se essa jornada de 40 horas é ultrapassada, a cada hora extra o ganho extra será de 50% a mais que uma hora trabalhado dentro das 40 horas. Assim em salario terá o valor de 40 vezes o valor do ganho por hora mais a hora extra acrescida de mais 50%.  

As variáveis são a quantidade de horas trabalhada e o valor pago por hora. É utilizado um if e else para distinguir se há acréscimo de horas extra ou apenas horas trabalhadas abaixo de 40. Se houver horas escedentes, cada horá terá um fator de 1,5 de aumento no valor de cada hora.

In [ ]:
def calculo_imc(peso, altura):
    print(peso/altura**2)
calculo_imc(altura=1.76, peso=68)
calculo_imc(68, 1.76)


21.952479338842977
21.952479338842977


Para cálculo do IMC foi criada a função onde posteriormente é declarado o valor de cada parâmetro para o cálculo ou apenas adicionado entre () o valor de cada parâmetro na ordem declarada dentro da função. Como no corpo da função ja tem o print, não há necessidade de declarar o return.

# **Condicionais**
## **Operadores Relacionais**
São expressões lógicas que relacionam variáveis e podem se **VERDADEIRAS** ou **FALSAS**. Por isso, também são chamados de operadores **Booleanos**. Em python temos os seguintes operadores relacionais:

* \> Maior que
* \>= Maior ou igual a
* \< Menor que 
* \<= Menor ou igual a 
* \== Igual a
* =! Diferente de 

Em python, quando escrevemos uma expressão Booleana com esses operadores, o programa vai nos retornar True(verdaeiro) ou False(falso).

In [ ]:
10>5

True

In [ ]:
10<5

False

In [ ]:
4==2+2

True

# **Estrutura Condicional**

Baseado numa decisão de condição:

Se estiver chovendo eu vou de carro, se não estiver chovendo eu não vou de carro.

Neste exemplo ir de carro ou não está condicionado ao tempo.



In [ ]:
nota = (float(input('Nota: ')))
if nota>=7.0:
  print('APROVADO!!')
else:
  print('REPROVADO!!')


Nota: 7.9
APROVADO!!


* **if** = se
* **else** = senão
* **elif** = senão, se - colocado após uma estrutura condicional **if**

In [ ]:
temp = float(input('Temperatura: '))
if temp >= 100:
  print('Gasoso')
elif temp >= 0:
  print('Líquido')
else:
  print('Sólido')


Temperatura: -5
Sólido


# **Laço "while"**
* Inicia a estrutura condicional com **while**;
* Na mesma linha escreve a condição;
* Em nova linha, com **IDENTAÇÃO**, adiciona os trechos que se repetirão até que a condição se torne **falsa**. Podemos adicionar até outros condicionais nesta parte. Assim o programa sai do laço e segue o executando o restante do código fora do laço.

## É importante que sempre haja um mecanismo de parada, senão o laço fica sendo executado infinitamente.


In [ ]:
N = 0
while N <= 10:
  print(N)
  N = N+1

1
2
3
4
5
6
7
8
9
10
11


A variável N é o contador. Em programação é comum utilizar **i** como contador, e costuma se iniciar em 0.

In [ ]:
i = 0
while i < 5:
  print('Esta é a iteração ',i)
  i = i+1

Esta é a iteração  0
Esta é a iteração  1
Esta é a iteração  2
Esta é a iteração  3
Esta é a iteração  4


# **Laço "for"**
O laço **"for"** repetes tantas vezes quanto houverem itens em uma lista (ou range). Por exemplo:

"Para cada iten desta lista, repita a execução desta ação."


In [ ]:
L = [1, 2, 3, 4, 5, 6, 7, 8]
for x in L:
  print(x**2)


1
4
9
16
25
36
49
64


In [ ]:
Y = ["people", 2, [0, 4], 5.4]
for x in Y:
  print(type(x))

<class 'str'>
<class 'int'>
<class 'list'>
<class 'float'>


# **Função "range()"** 

Muito utilizada em conjunto com **"for"**, permite criar sequências de números inteiros.

Esta função pode ser chamada de 3 formas:

* range(valor_final): cria um sequência de números inteiros começando em 0 e terminando no valor anterior ao valor_final.

In [2]:
for i in range(5):
  print(i)

0
1
2
3
4
