<a href="https://colab.research.google.com/github/gregorimaia/Engenharia_Aeroespacial/blob/main/Python_Instructions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tipos de Variáveis**
## Variável Inteira (int): Utilizada para números inteiros;
## Variável Decimal (Flutuante, float);
## Variável String (str);
## Variável Dictionary (dict);
## Variável Booleana (bool);
## Variáveis de lista: list e tuple;

Para itendificar o tipo de variável utiliza-se o comando type().


In [ ]:
# (int) Números inteiros
ano = 2022
print(ano)
print(type(ano))

# (float) Números decimais ou fracionários
idade = 26.5
print(idade)
print(type(idade))

# (str) Caracteres ou texto
nome = 'Gregori'
print(nome)
print(type(nome))

# (dict) Pares de informações relacionando-as
dict1= {'Nome':'Gregori', 'Idade':57, 'Nota':8.5}
print(dict1, type(dict1))

# (bool) Assume valores de verdadeiro (1) ou falso (0)
CodeQ = True
print(CodeQ, type(CodeQ))

# (list, tuple) Lista de outros tipos de variáveis
# (list) os elementos podem ser alterados 
# (tuple) os elementos não podem ser alterados
alunos = ['Ana', 'Mathias', 'Grégori']
print(alunos, type(alunos))

notas = (8.9, 9.5, 8.5)
print(notas, type(notas))


2022
<class 'int'>
26.5
<class 'float'>
Gregori
<class 'str'>
{'Nome': 'Gregori', 'Idade': 57, 'Nota': 8.5} <class 'dict'>
True <class 'bool'>
['Ana', 'Mathias', 'Grégori'] <class 'list'>
(8.9, 9.5, 8.5) <class 'tuple'>


# **Comando** _*append*_ **adiciona itens à uma lista já existente, geralmente utilizado dentro de laços.**


In [ ]:
lista = [] # Criação de uma lista vazia
for i in range(10): # Criação de um loop
    y = 2*i
    lista.append(y) # Adicionando o valor y á lista
print(lista)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


# **Vetores e Matrizes**


* listas

In [ ]:
numeros = [1, 2 , 3, 4]
print(numeros)
# os elementos da lista são contados desde o zero
# Posso determinar um valor a ser apresentado da lista
print(numeros[0])  
print(numeros[2])
type(numeros)

[1, 2, 3, 4]
1
3


list

In [ ]:
# posso modificar alguma variável da lista
numeros[3] = 8
print(numeros)

[1, 2, 3, 8]


* _*array*_

In [ ]:
import numpy as np # Para não ter que ficar escrevedo numpy toda hora, mas np
# arrays são variáveis da biblioteca numpy e servirão como vetores
# multiplicaçoes matriciais só podem ser aplicadas à arrays

numeros = np.array([1,2,3,4])
Matriz = np.array([[1,0,5],[0,1,8],[2,9,3]])

print(numeros, type(numeros))
print(Matriz, type(Matriz)) # Não há um type específico para matrizes, é identificado com array.
print(Matriz[1]) # Ao escolher um item da matriz, será apresentado por linha.

[1 2 3 4] <class 'numpy.ndarray'>
[[1 0 5]
 [0 1 8]
 [2 9 3]] <class 'numpy.ndarray'>
[0 1 8]


* linspace
Vetor composto por números **igualmente espaçados** entre um determinado intervalo. Será bastante utilizado para criação de um intervalo de integração que será utilizado com a função **_*odeint*_**.

In [ ]:
T1 = np.linspace(1,5,30) # Vetor começando em 1 até 5 apresentando 30 ...
# termos igualmente espaçados
print(T1, type(T1), len(T1))
# Se não determinar o número de termos, automaticamente aparecerá 50 termos.

[1.         1.13793103 1.27586207 1.4137931  1.55172414 1.68965517
 1.82758621 1.96551724 2.10344828 2.24137931 2.37931034 2.51724138
 2.65517241 2.79310345 2.93103448 3.06896552 3.20689655 3.34482759
 3.48275862 3.62068966 3.75862069 3.89655172 4.03448276 4.17241379
 4.31034483 4.44827586 4.5862069  4.72413793 4.86206897 5.        ] <class 'numpy.ndarray'> 30


* arange

In [ ]:
import numpy as np
numeros = np.arange(3) # Quando não especificamos 2 valores, começamos de 0.
print(numeros, type(numeros))

numeros2 = np.arange(3, 9) # se não esécificar o intervalo, vai apresentar unidade por unidade
print(numeros2)

numeros3 = np.arange(3, 9, 0.5) # (início, final-1(intervalo), intervalo)
print(numeros3, len(numeros3))

[0 1 2] <class 'numpy.ndarray'>
[3 4 5 6 7 8]
[3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5] 12


Note:
* Comprimento (length) de um vetor: retorna o número de elementos de um vetor, ou o número de linhas de uma matriz. Utiliza-se o comando len(A).

# **Funções**
Dentro de uma linguagem de programação, Funções são grupos de códigos que realizam algumas tarefas que, geralmente, seriam executadas várias vezes dentro de um mesmo código. A forma de escrita de uma função é separada em 4 partes:

**NOME, PARÂMETROS, CORPO E RESPOSTA (OURETORNO)**

In [ ]:
# def nome(parametros):
#     corpo
#     return  (resposta)

**NOME**

É o nome pelo qual a função será chamada em um código

**PARÂMETROS**

São as variáveis externas à função, que são necessárias para que a função seja executada (variáveis independentes). Nem sempre será necessário declarar parâmetros, poi podemos "chamar" funções para que sejam simplesmente executadas.

**CORPO**

É onde os argumentos da função serão utilizados para a execução da função.

***RESPOSTA**

É o retorno da função, ou seja, o que a função retornará de resposta. Assim como os parâmetros, nem sempre será necessário um comando de resposta, isso dependerá do objetvo da função.


In [1]:
def calcular_pagamento(qtd_horas, valor_hora):
  horas = float(qtd_horas)
  taxa = float(valor_hora)
  if horas <=40:
    salario=horas*taxa
  else:
    h_excd = horas - 40
    salario = 40*taxa+(h_excd*(1.5*taxa))
  return salario